Check the value of conf-bin, as some tests will fail if it is not set properly.

diff --git a/tests/01-misc b/tests/01-misc
--- a/tests/01-misc
+++ b/tests/01-misc
@@ -126,6 +126,14 @@ if [ ! -x "${EZBIN}/ezmlm-make" ]; then
 	exit 99
 fi
 
+if [ x`head -n 1 ${EZBIN}/conf-bin` != x"$EZBIN" ]; then
+	${ECHO} "ezmlm-idx programs are configured to execute in a different"
+	${ECHO} "directory (`head -n 1 ${EZBIN}/conf-bin`) from the directory"
+	${ECHO} "in which they are residing ($EZBIN)."
+	${ECHO} "This will cause some tests to fail."
+	exit 99
+fi
+
 ########################
 # remove old test list #
 ########################
