tests: Remove the program name settings
All *NIX systems have the common programs in the path, and since the
tests no longer use delivery through qmail, full program paths are not
needed.  If a tester finds a problem with this, he can use a function to
define a replacement.

diff --git a/tests/02-functions b/tests/02-functions
--- a/tests/02-functions
+++ b/tests/02-functions
@@ -1,39 +1,39 @@
 fatal() {
   for line in "$@"; do
-    ${ECHO} "$line" >&2
+    echo "$line" >&2
   done
   exit 100;
 }
 
 grephdr() {
   # Search for the header line, and produce an error if it didn't match.
-  ${GREP} "^$*$" "$QQHDR" >/dev/null 2>&1 || \
+  grep "^$*$" "$QQHDR" >/dev/null 2>&1 || \
   {
-    ${ECHO} "Header is missing or wrong $1 line:";
-    ${GREP} -i "^$1" "$QQHDR"
+    echo "Header is missing or wrong $1 line:";
+    grep -i "^$1" "$QQHDR"
     BUG="${BUG} headers"
     prompt "..............: "
   }
   # Remove any found lines from the header file
-  ${GREP} -iv "^$1" "$QQHDR" >"${TMP}hdr"
-  ${MV} -f "${TMP}hdr" "$QQHDR"
+  grep -iv "^$1" "$QQHDR" >"${TMP}hdr"
+  mv -f "${TMP}hdr" "$QQHDR"
 }
 
 grepbody() {
-  ${GREP} "^$*$" "$QQBODY" >/dev/null 2>&1 || \
+  grep "^$*$" "$QQBODY" >/dev/null 2>&1 || \
   {
-    ${ECHO} "Body is missing or wrong $1 line:";
-    ${GREP} -i "^$1" "$QQBODY"
+    echo "Body is missing or wrong $1 line:";
+    grep -i "^$1" "$QQBODY"
     BUG="${BUG} body"
     prompt "..............: "
   }
 }
 
 grepbodynot() {
-  ${GREP} "^$*" "$QQBODY" >/dev/null 2>&1 && \
+  grep "^$*" "$QQBODY" >/dev/null 2>&1 && \
   {
-    ${ECHO} "Body contains extraneous $1 line:";
-    ${GREP} -i "^$1" "$QQBODY"
+    echo "Body contains extraneous $1 line:";
+    grep -i "^$1" "$QQBODY"
     BUG="${BUG} body"
     prompt "..............: "
   }
@@ -68,8 +68,8 @@ grephdr_empty() {
   # Use this after all other grephdr checks to ensure nothing else was output
   test -s "$QQHDR" && \
   {
-    ${ECHO} "Headers contained extra lines:"
-    ${CAT} "$QQHDR"
+    echo "Headers contained extra lines:"
+    cat "$QQHDR"
     BUG="${BUG} headers"
   }
 }
@@ -77,7 +77,7 @@ grephdr_empty() {
 checkenv()
 {
   msg="$1"
-  ${HEAD} -n 1 "$QQENV" | grep "^F$2$" >/dev/null \
+  head -n 1 "$QQENV" | grep "^F$2$" >/dev/null \
   || fatal "envelope for $msg has wrong sender"
   test $# = $(wc -l <"$QQENV") \
   || fatal "envelope for $msg has wrong number of recipients"
@@ -93,44 +93,44 @@ checkenv()
 ###############################
 make_body()
 {
-  ${ECHO} "This is a simple message body"
-  ${ECHO} "--bound123ary"
-  ${ECHO} "Content-type: Text/pLAIn"
-  ${ECHO}
-  ${ECHO} "plain text"
-  ${ECHO} "--bound123ary"
-  ${ECHO} "Content-type: texT/Html"
-  ${ECHO}
-  ${ECHO} "html text"
-  ${ECHO} "--bound123ary--"
-  ${ECHO}
-  ${ECHO} "junk after boundary"
+  echo "This is a simple message body"
+  echo "--bound123ary"
+  echo "Content-type: Text/pLAIn"
+  echo
+  echo "plain text"
+  echo "--bound123ary"
+  echo "Content-type: texT/Html"
+  echo
+  echo "html text"
+  echo "--bound123ary--"
+  echo
+  echo "junk after boundary"
   return 0
 }
 
 qqclean()
 {
-  ${RM} -f "$QQBODY" "$QQENV" "$QQHDR" "$QQMSG" "$QQMSG".*
+  rm -f "$QQBODY" "$QQENV" "$QQHDR" "$QQMSG" "$QQMSG".*
 }
 
 make_message()
 {
-  ${ECHO} "ReCEIved: #LAST#"
-  ${ECHO} "ReCeIved: #PENULTIMATE#"
-  ${ECHO} "retuRN-RECeipt-to: nobody"
-  ${ECHO} "To: $TO"
-  ${ECHO} "CC: "
-  ${ECHO} " $CC"
-  ${ECHO} "FROM: $FROM"
+  echo "ReCEIved: #LAST#"
+  echo "ReCeIved: #PENULTIMATE#"
+  echo "retuRN-RECeipt-to: nobody"
+  echo "To: $TO"
+  echo "CC: "
+  echo " $CC"
+  echo "FROM: $FROM"
   if [ ! -z "$CONTENT" ]; then
-	${ECHO} "MIME-Version: 1.0"
-	${ECHO} "Content-type: $CONTENT;"
-	${ECHO} " boundary=bound123ary${AFTERBOUND}"
+	echo "MIME-Version: 1.0"
+	echo "Content-type: $CONTENT;"
+	echo " boundary=bound123ary${AFTERBOUND}"
   fi
   if [ ! -z "$SUBJECT" ]; then
-	${ECHO} "Subject: $SUBJECT"
+	echo "Subject: $SUBJECT"
   fi
-  ${ECHO}
+  echo
   make_body
   return 0
 }
@@ -140,18 +140,18 @@ make_message()
 #########################
 exists() {
   for file in "$@"; do
-    ${TEST} -e "$file" || return 1
+    test -e "$file" || return 1
   done
   return 0
 }
 
 msgexists() {
-  ${TEST} -s "$QQMSG" -a -s "${QQENV}"
+  test -s "$QQMSG" -a -s "${QQENV}"
 }
 
 #######################################
 # Extract parts of the message header #
 #######################################
 gethdr() {
-    ${SED} -e "/^$1:/!d; s/[^ ]* *//;" "$QQHDR"
+    sed -e "/^$1:/!d; s/[^ ]* *//;" "$QQHDR"
 }
diff --git a/tests/120-ezmlm-send b/tests/120-ezmlm-send
--- a/tests/120-ezmlm-send
+++ b/tests/120-ezmlm-send
@@ -7,13 +7,13 @@
   SENDER="${SND}@$HOST"
   ${EZBIN}/ezmlm-sub "$DIR" "$SENDER"
 # set up prefix
-  ${ECHO} "[PFX]" > "${DIR}/prefix"
+  echo "[PFX]" > "${DIR}/prefix"
 # set up trailer
   mkdir -p "${DIR}/text"
-  { ${ECHO} "--- TRAILER ---"; ${ECHO}; } > "${DIR}/text/trailer"
+  { echo "--- TRAILER ---"; echo; } > "${DIR}/text/trailer"
   touch "$DIR"/addtrailer
 # test
-  { ${ECHO} "X-num: msg1"; make_message; } | \
+  { echo "X-num: msg1"; make_message; } | \
 	${EZBIN}/ezmlm-send "$DIR" >"$ERR" 2>&1 || \
 	fatal "failed to accept normal message"
   if [ `cat "${DIR}/num"` != "1:1" ]; then
@@ -22,50 +22,50 @@
   if [ ! -x "${DIR}/archive/0/01" ]; then
 	fatal "failed to archive normal message"
   fi
-  ${GREP} "1:" "${DIR}/archive/0/index" >/dev/null 2>&1 || \
+  grep "1:" "${DIR}/archive/0/index" >/dev/null 2>&1 || \
 	fatal "failed to index archive"
 
-  ${GREP} "$SENDER" "$QQENV" >/dev/null 2>&1 ||
+  grep "$SENDER" "$QQENV" >/dev/null 2>&1 ||
 	fatal "failed to deliver message to subscriber"
   checkenv msg1 "$LOC-return-1-@$HOST-@\\[\\]" "$SENDER"
 
 # make sure headeradd was done
-  ${GREP} -i 'precedence: bulk' "$QQMSG" >/dev/null 2>&1 ||
+  grep -i 'precedence: bulk' "$QQMSG" >/dev/null 2>&1 ||
 	fatal "failed to add headeradd"
 # check on received: header handling
-  ${GREP} '#PENULTIMATE#' "$QQMSG" >/dev/null && \
+  grep '#PENULTIMATE#' "$QQMSG" >/dev/null && \
 	fatal "-r failed to remove received header"
-  ${GREP} '#LAST#' "$QQMSG" >/dev/null || \
+  grep '#LAST#' "$QQMSG" >/dev/null || \
 	fatal "-r failed to leave last received header"
-  ${GREP} 'Subject:' "$QQMSG" | ${GREP} 'PFX' >/dev/null 2>&1 || \
+  grep 'Subject:' "$QQMSG" | grep 'PFX' >/dev/null 2>&1 || \
 	fatal "failed to add subject prefix"
 	# the trailer should be a MIME part, so not at the very end
-  ${TAIL} -n 6 "$QQMSG" | ${HEAD} -n 2 | ${GREP} 'TRAILER' >/dev/null 2>&1 || \
+  tail -n 6 "$QQMSG" | head -n 2 | grep 'TRAILER' >/dev/null 2>&1 || \
 	fatal "failed to add trailer"
 
-  ${RM} -f "${DIR}/indexed"
-  ${RM} -f "${DIR}/archived"
+  rm -f "${DIR}/indexed"
+  rm -f "${DIR}/archived"
 
 # test to see that trailer is added to nom-mime messages
   CONTENT=''
-  { ${ECHO} "X-num: msg5"; make_message; } | \
+  { echo "X-num: msg5"; make_message; } | \
 	${EZBIN}/ezmlm-send "$DIR" >"$ERR" 2>&1  || \
 	fatal "failed to accept non-mime message"
 
   checkenv msg5 "$LOC-return-2-@$HOST-@\\[\\]" "$SENDER"
-  ${GREP} 'TRAILER' "$QQMSG" >/dev/null 2>&1 || \
+  grep 'TRAILER' "$QQMSG" >/dev/null 2>&1 || \
 	fatal "failed to add trailer to non-mime message"
 
 # test to see that trailer is suppressed for multipart/signed
   CONTENT='multipart/signed'
-  { ${ECHO} "X-num: msg6"; make_message; } | \
+  { echo "X-num: msg6"; make_message; } | \
 	${EZBIN}/ezmlm-send "$DIR" >"$ERR" 2>&1  || \
 	fatal "failed to accept multipart/signed message"
 
   checkenv msg6 "$LOC-return-3-@$HOST-@\\[\\]" "$SENDER"
-  ${GREP} 'TRAILER' "$QQMSG" >/dev/null 2>&1 && \
-	{ ${ECHO} "failed to suppress trailer for multipart/signed message"; \
-	  ${ECHO} "                      0.31 bug fixed in 0.316/0.323";
+  grep 'TRAILER' "$QQMSG" >/dev/null 2>&1 && \
+	{ echo "failed to suppress trailer for multipart/signed message"; \
+	  echo "                      0.31 bug fixed in 0.316/0.323";
 	  BUG="${BUG}_signed"; \
 	  prompt "ezmlm-send ......:    "; }
 
@@ -74,9 +74,9 @@
 
 # test content-type with something after boundary=xxx
   AFTERBOUND=';micalg=pgp-md5'
-  ${ECHO} "text/html" > "$DIR"/mimeremove
+  echo "text/html" > "$DIR"/mimeremove
   make_message | ${EZBIN}/ezmlm-send "$DIR" >"$ERR" 2>&1  || \
-	{ ${ECHO} "err with text after boundary: 0.30 bug fixed in 0.322"
+	{ echo "err with text after boundary: 0.30 bug fixed in 0.322"
 	  prompt "ezmlm-send.........   "
 	  BUG="${BUG} send_bound"
 	}
@@ -84,72 +84,72 @@
 
 # restore
   AFTERBOUND=''
-  ${ECHO} "1:1" > "${DIR}/num"
-  ${RM} "$DIR"/mimeremove
+  echo "1:1" > "${DIR}/num"
+  rm "$DIR"/mimeremove
 
 # -r => don't trim received headers
-  { ${ECHO} "X-num: msg2"; make_message; } | \
+  { echo "X-num: msg2"; make_message; } | \
 	${EZBIN}/ezmlm-send -r "$DIR" >"$ERR" 2>&1 || \
 	fatal "failed to accept normal message 2"
   checkenv msg2 "$LOC-return-2-@$HOST-@\\[\\]" "$SENDER"
 
-  ${GREP} "2:" "${DIR}/archive/0/index" >/dev/null 2>&1 && \
+  grep "2:" "${DIR}/archive/0/index" >/dev/null 2>&1 && \
 	fatal "indexed message with DIR/indexed missing"
-  ${GREP} "msg2" ${DIR}/archive/0/* >/dev/null 2>&1 && \
+  grep "msg2" ${DIR}/archive/0/* >/dev/null 2>&1 && \
 	fatal "archived message with DIR/archived missing"
 
-  ${GREP}  '#PENULTIMATE#' "$QQMSG" >/dev/null 2>&1 || \
+  grep  '#PENULTIMATE#' "$QQMSG" >/dev/null 2>&1 || \
 	fatal "-r failed to leave received header"
 
 # -C eliminate SENDER from addressees
-  { ${ECHO} "X-num: msg3"; make_message; } | \
+  { echo "X-num: msg3"; make_message; } | \
 	${EZBIN}/ezmlm-send -C "$DIR" >"$ERR" 2>&1 || \
 	fatal "failed to accept normal message 3"
   checkenv msg3 "$LOC-return-3-@$HOST-@\\[\\]" "$SENDER"
   ${EZBIN}/ezmlm-unsub "$DIR" "$SENDER"
 
-  ${GREP} T"$SENDER" "$QQENV" >/dev/null 2>&1 || \
-	{ ${ECHO} "failed to include sender (-C is ignored)"; \
+  grep T"$SENDER" "$QQENV" >/dev/null 2>&1 || \
+	{ echo "failed to include sender (-C is ignored)"; \
 	  BUG="${BUG}_noself"; \
 	  prompt "ezmlm-send:           "; }
 
 # make sure headerremove was done
-  ${GREP} -i 'return-receipt-to' < "${DIR}/archive/0/01" >/dev/null &&
+  grep -i 'return-receipt-to' < "${DIR}/archive/0/01" >/dev/null &&
 	fatal "failed to remove headerremove"
 
 # test mimeremove
   touch "${DIR}/archived" "${DIR}/indexed"
-  ${ECHO} "teXT/hTml" > "${DIR}/mimeremove"
-  { ${ECHO} "X-num: mimeremove"; make_message; } | \
+  echo "teXT/hTml" > "${DIR}/mimeremove"
+  { echo "X-num: mimeremove"; make_message; } | \
 	${EZBIN}/ezmlm-send "$DIR" >"$ERR" 2>&1 || \
 	fatal "failed to accept mimeremove message"
   checkenv mimeremove "$LOC-return-4-@$HOST-@\\[\\]"
-  ${GREP} -i 'text/html' < "${DIR}/archive/0/04" >/dev/null &&
+  grep -i 'text/html' < "${DIR}/archive/0/04" >/dev/null &&
 	fatal "failed to remove mimeremove part"
 
 # test mimekeep
   touch "${DIR}/archived" "${DIR}/indexed"
-  ${ECHO} "multipart/mixed" > "${DIR}/mimekeep"
-  ${ECHO} "teXT/plain" >> "${DIR}/mimekeep"
-  { ${ECHO} "X-num: mimekeep"; make_message; } | \
+  echo "multipart/mixed" > "${DIR}/mimekeep"
+  echo "teXT/plain" >> "${DIR}/mimekeep"
+  { echo "X-num: mimekeep"; make_message; } | \
         ${EZBIN}/ezmlm-send "$DIR" >"$ERR" 2>&1 || \
 	fatal "failed to accept mimekeep message"
   checkenv mimekeep "$LOC-return-5-@$HOST-@\\[\\]"
-  ${GREP} -i 'text/html' < "${DIR}/archive/0/05" >/dev/null &&
+  grep -i 'text/html' < "${DIR}/archive/0/05" >/dev/null &&
 	fatal "failed to remove mimekeep part"
 
 # test headerkeep
-  ${ECHO} subject >"$DIR"/headerkeep
-  ${ECHO} from >>"$DIR"/headerkeep
-  ${ECHO} x-num >>"$DIR"/headerkeep
-  { ${ECHO} "X-num: keeptest"; make_message; } | \
+  echo subject >"$DIR"/headerkeep
+  echo from >>"$DIR"/headerkeep
+  echo x-num >>"$DIR"/headerkeep
+  { echo "X-num: keeptest"; make_message; } | \
 	${EZBIN}/ezmlm-send -C "$DIR" >"$ERR" 2>&1 || \
 	fatal "failed to accept keeptest message"
   checkenv keeptest "$LOC-return-6-@$HOST-@\\[\\]"
-  ${GREP} -i '^x-num: keeptest' < "${DIR}/archive/0/06" >/dev/null ||
+  grep -i '^x-num: keeptest' < "${DIR}/archive/0/06" >/dev/null ||
 	fatal "failed to keep header in headerkeep"
-  ${GREP} -i '^return-receipt-to' < "${DIR}/archive/0/06" >/dev/null &&
+  grep -i '^return-receipt-to' < "${DIR}/archive/0/06" >/dev/null &&
 	fatal "failed to remove header not in headerkeep"
-  ${RM} "$DIR"/headerkeep
+  rm "$DIR"/headerkeep
 
-  ${ECHO} "OK"
+  echo "OK"
diff --git a/tests/160-ezmlm-manage b/tests/160-ezmlm-manage
--- a/tests/160-ezmlm-manage
+++ b/tests/160-ezmlm-manage
@@ -22,7 +22,7 @@
   checkenv unsubscribe-nounsubconfirm "$LOC-return-@$HOST" "$SENDER"
   ${EZBIN}/ezmlm-issubn "$DIR" && \
 	fatal "unsubscribe with nounsubconfirm failed"
-  ${RM} "$DIR"/nounsubconfirm
+  rm "$DIR"/nounsubconfirm
 
   LOCAL="$LOC-digest-subscribe"
   DEFAULT='digest-subscribe'
@@ -33,7 +33,7 @@
   DEFAULT='deny-subscribe'
   ${EZBIN}/ezmlm-manage "$DIR" </dev/null >/dev/null 2>&1 && \
 	{
-	 ${ECHO} "Deny open to regular subscribers: 0.31 bug, OK in 0.321."
+	 echo "Deny open to regular subscribers: 0.31 bug, OK in 0.321."
 	 prompt "ezmlm-manage ...      "
 	 BUG="${BUG} deny"
 	}
@@ -45,15 +45,15 @@
   checkenv admin-deny "$LOC-deny-return-@$HOST" "$SENDER"
 
 # make non-moderated
-  ${RM} -f "${DIR}/modsub" || \
-	{ ${ECHO} "Failed to remove DIR/modsub"; exit 99; }
+  rm -f "${DIR}/modsub" || \
+	{ echo "Failed to remove DIR/modsub"; exit 99; }
 
 # make non-remote
-  ${RM} -f "${DIR}/remote" || \
-	{ ${ECHO} "Failed to remove DIR/remote"; exit 99; }
+  rm -f "${DIR}/remote" || \
+	{ echo "Failed to remove DIR/remote"; exit 99; }
   ${EZBIN}/ezmlm-manage "$DIR" </dev/null > "$ERR" 2>&1 && \
 	{
-	 ${ECHO} "Deny even without remote/modsub: 0.31 bug, OK in 0.321."
+	 echo "Deny even without remote/modsub: 0.31 bug, OK in 0.321."
 	 prompt "ezmlm-manage ...      "
 	 BUG="${BUG} deny"
 	}
@@ -63,7 +63,7 @@
   ${EZBIN}/ezmlm-unsub "$DIR" mod "$SENDER" || exit 100
   SENDER="${SND}@$HOST"		# restore order
   touch "${DIR}/remote" || \
-	{ ${ECHO} "Failed to remove DIR/remote"; exit 99; }
+	{ echo "Failed to remove DIR/remote"; exit 99; }
   LOCAL="$LOC-digest-subscribe"
 	DEFAULT='digest-subscribe'
 
@@ -80,35 +80,35 @@
   checkenv digest-subscribe-nosubconfirm "$LOC-digest-return-@$HOST" "$SENDER"
   ${EZBIN}/ezmlm-issubn "$DIR" digest || \
 	fatal "digest-subscribe with nosubconfirm failed"
-  ${RM} "$DIR"/nosubconfirm
+  rm "$DIR"/nosubconfirm
 
   ${EZBIN}/ezmlm-unsub "$DIR" digest "$SENDER"
   touch "${DIR}/modsub" || \
-	{ ${ECHO} "Failed to restore DIR/modsub"; exit 99; }
+	{ echo "Failed to restore DIR/modsub"; exit 99; }
 
   SENDER="${MAN}@$HOST"
 
-  ${ECHO} "X-num: sub1" > "$TMP"
-  ${ECHO} "From: Mr. User requests <${MAN}@$HOST>" >> "$TMP"
-  ${ECHO} >> "$TMP"
+  echo "X-num: sub1" > "$TMP"
+  echo "From: Mr. User requests <${MAN}@$HOST>" >> "$TMP"
+  echo >> "$TMP"
   ${EZBIN}/ezmlm-manage "$DIR" < "$TMP" \
 		>"$ERR" 2>&1 || \
 	fatal "digest-subscribe with request failed"
   checkenv sub1 "$LOC-digest-return-@$HOST" "$SENDER"
 
-  ${GREP} T"${MAN}@$HOST" "$QQENV" >/dev/null 2>&1 || \
+  grep T"${MAN}@$HOST" "$QQENV" >/dev/null 2>&1 || \
 	fatal "failed getting digest-subscribe confirm request"
 
   # Add moderator
   ${EZBIN}/ezmlm-sub "$DIR" mod "${MOD}@$HOST"
 
-  LOCAL=`${GREP} "Reply-To:" "$QQMSG" | cut -d' ' -f2 | cut -d'@' -f1` || \
+  LOCAL=`grep "Reply-To:" "$QQMSG" | cut -d' ' -f2 | cut -d'@' -f1` || \
 	fatal "failed to find confirm address in -subscribe reply"
   qqclean
-  DEFAULT=`${ECHO} "$LOCAL" | cut -c"$LOCLEN"-`
-  ${ECHO} "X-num: sub3" > "$TMP"
-  ${ECHO} "From: Mr. User confirms <$SENDER>" >> "$TMP"
-  ${ECHO} >> "$TMP"
+  DEFAULT=`echo "$LOCAL" | cut -c"$LOCLEN"-`
+  echo "X-num: sub3" > "$TMP"
+  echo "From: Mr. User confirms <$SENDER>" >> "$TMP"
+  echo >> "$TMP"
   ${EZBIN}/ezmlm-manage "$DIR" < "$TMP" \
 		>"$ERR" 2>&1 || \
 	fatal "failed to send user conf for sub1"
@@ -118,16 +118,16 @@
   SENDER="${MOD}@$HOST"
   ${EZBIN}/ezmlm-issubn "$DIR" && \
 	fatal "unsub without mod for moderated list failed"
-  ${GREP} 'sub3' "$QQMSG" >/dev/null 2>&1 || \
+  grep 'sub3' "$QQMSG" >/dev/null 2>&1 || \
 	fatal "failed getting subscribe moderation confirm request"
 
   # confirm subscription request
-  LOCAL=`${GREP} "Reply-To:" "$QQMSG" | cut -d' ' -f2 | cut -d'@' -f1` || \
+  LOCAL=`grep "Reply-To:" "$QQMSG" | cut -d' ' -f2 | cut -d'@' -f1` || \
 	fatal "no confirm address in sub3 mod confirm request"
-  DEFAULT=`${ECHO} "$LOCAL" | cut -c"$LOCLEN"-`
-  ${ECHO} "X-num: modR1" > "$TMP"
-  ${ECHO} "FROM: moderator agrees <$SENDER>" >> "$TMP"
-  ${ECHO} >> "$TMP"
+  DEFAULT=`echo "$LOCAL" | cut -c"$LOCLEN"-`
+  echo "X-num: modR1" > "$TMP"
+  echo "FROM: moderator agrees <$SENDER>" >> "$TMP"
+  echo >> "$TMP"
   ${EZBIN}/ezmlm-manage ${SW_FROM} "$DIR" < "$TMP"\
 		>/dev/null 2>&1 || \
 	fatal "failed to send digest sub mod accept for sub3"
@@ -137,15 +137,15 @@
   ${EZBIN}/ezmlm-sub "$DIR" "$SENDER"
   LOCAL="$LOC-unsubscribe"
   DEFAULT='unsubscribe'
-  ${ECHO} "X-num: sub2" > "$TMP"
+  echo "X-num: sub2" > "$TMP"
   ${EZBIN}/ezmlm-manage "$DIR" < "$TMP" >"$ERR" 2>&1 || \
 	fatal "unsubscribe request failed"
   checkenv sub2 "$LOC-return-@$HOST" "$SENDER"
 
-  LOCAL=`${GREP} "Reply-To:" "$QQMSG" | cut -d' ' -f2 | cut -d'@' -f1` || \
+  LOCAL=`grep "Reply-To:" "$QQMSG" | cut -d' ' -f2 | cut -d'@' -f1` || \
 	fatal "failed to find confirm address in -unsubscribe reply"
-  DEFAULT=`${ECHO} "$LOCAL" | cut -c"$LOCLEN"-`
-  ${ECHO} "X-num: sub4" > "$TMP"
+  DEFAULT=`echo "$LOCAL" | cut -c"$LOCLEN"-`
+  echo "X-num: sub4" > "$TMP"
   ${EZBIN}/ezmlm-manage "$DIR" < "$TMP" >/dev/null 2>&1 || \
 	fatal "failed to send conf for sub2"
   checkenv sub4 "$LOC-return-@$HOST" "$SENDER"
@@ -153,17 +153,17 @@
 # -get function for backwards compatibility
   LOCAL="$LOC-get.1"
   DEFAULT='get.1'
-  ${ECHO} "X-num: manget1" > "$TMP"
+  echo "X-num: manget1" > "$TMP"
   ${EZBIN}/ezmlm-manage "$DIR" < "$TMP" >"$ERR" 2>&1 || \
 	fatal "get failed"
   checkenv get.1 "$LOC-return-@$HOST" "$SENDER"
 
   # Check -get.1 reply
-  ${GREP} 'msg1' "$QQMSG" >/dev/null || \
+  grep 'msg1' "$QQMSG" >/dev/null || \
 	fatal "get.1 failed to return archived message"
 
 # -C should disable it
   ${EZBIN}/ezmlm-manage -C "$DIR" < "$TMP" >"$ERR" 2>&1 && \
 	fatal "-C failed to disable -get"
 
-  ${ECHO} "OK"
+  echo "OK"
