Removed all references to "inhost" which was completely unused but still referenced in documentation and tests.

diff --git a/tests/105-qmail-version b/tests/105-qmail-version
--- a/tests/105-qmail-version
+++ b/tests/105-qmail-version
@@ -67,10 +67,10 @@ fi
     ${ECHO} "|/${EZBIN}/ezmlm-return '${DIR}'" >> "${DIR}/digest/bouncer"
   fi
 
-# if testing qmail>=1.02, remove inlocal/inhost - shouldn't be used
+# if testing qmail>=1.02, remove inlocal - shouldn't be used
   if [ "$QMVER" = "n" ]; then
-	${RM} -f "${DIR}/inlocal" "${DIR}/inhost" > /dev/null || \
-	  { ${ECHO} "failed to remove inlocal/inhost for testlist"; exit 100; }
+	${RM} -f "${DIR}/inlocal" > /dev/null || \
+	  { ${ECHO} "failed to remove inlocal for testlist"; exit 100; }
   fi
 
 ###########################
diff --git a/tests/135-ezmlm-make b/tests/135-ezmlm-make
--- a/tests/135-ezmlm-make
+++ b/tests/135-ezmlm-make
@@ -56,10 +56,10 @@ ${ECHO} "OK"
     ${ECHO} "|/${EZBIN}/ezmlm-return -d '${DIR}'" >> "${DIR}/digest/bouncer"
   fi
 
-# if testing qmail>=1.02, remove inlocal/inhost - shouldn't be used
+# if testing qmail>=1.02, remove inlocal - shouldn't be used
   if [ "$QMVER" = "n" ]; then
-	${RM} -f "${DIR}/inlocal" "${DIR}/inhost" > /dev/null || \
-	  { ${ECHO} "failed to remove inlocal/inhost for testlist"; exit 100; }
+	${RM} -f "${DIR}/inlocal" > /dev/null || \
+	  { ${ECHO} "failed to remove inlocal for testlist"; exit 100; }
   fi
 
 fi
