Converted all remaining ${ECHO}+exit 100 instances to use fatal.

diff --git a/tests/110-ezmlm-reject b/tests/110-ezmlm-reject
--- a/tests/110-ezmlm-reject
+++ b/tests/110-ezmlm-reject
@@ -18,43 +18,36 @@ if [ "$SECT" = "1" ]; then
   BODY=''
 
   ${EZBIN}/ezmlm-reject "${DIR}" </dev/null >/dev/null 2>&1 && \
-        { ${ECHO} "failed to reject missing \$SENDER"; \
-          exit 100; }
+        fatal "failed to reject missing \$SENDER"
 
   SENDER=''; export SENDER
   ${EZBIN}/ezmlm-reject "${DIR}" </dev/null >/dev/null 2>&1 && \
-        { ${ECHO} "failed to reject empty sender"; \
-          exit 100; }
+        fatal "failed to reject empty sender"
 
   SENDER="${SND}@$HOST"; export SENDER
 
 # with directory
   make_message | ${EZBIN}/ezmlm-reject "${DIR}" || \
-	{ ${ECHO} "failed to accept good message with dir"; \
-	exit 100; }
+	fatal "failed to accept good message with dir"
 # without directory
 
   make_message | ${EZBIN}/ezmlm-reject || \
-	{ ${ECHO} "failed to accept good message without dir: $?"; \
-	exit 100; }
+	fatal "failed to accept good message without dir: $?"
 
 #too small
   ${ECHO} "5000:1000" > "${DIR}/msgsize"
   { make_message | ${EZBIN}/ezmlm-reject "${DIR}"; } >/dev/null 2>&1 && \
-	{ ${ECHO} "ezmlm-reject failed to reject too small message"; \
-		exit 100; }
+	fatal "ezmlm-reject failed to reject too small message"
 
 # just right
   ${ECHO} "500:5" > "${DIR}/msgsize"
   make_message | ${EZBIN}/ezmlm-reject "${DIR}" || \
-	{ ${ECHO} "failed to accept message of ok size"; \
-	exit 100; }
+	fatal "failed to accept message of ok size"
 
 #too large
   ${ECHO} "20:10" > "${DIR}/msgsize"
   { make_message  | ${EZBIN}/ezmlm-reject "${DIR}"; } > /dev/null 2>&1 && \
-        { ${ECHO} "ezmlm-reject failed to reject too large message"; \
-                exit 100; }
+        fatal "ezmlm-reject failed to reject too large message"
 
 # restore
   ${RM} -f "${DIR}/msgsize"
@@ -62,20 +55,16 @@ if [ "$SECT" = "1" ]; then
 # without subject
   SUBJECT=''
    { make_message  | ${EZBIN}/ezmlm-reject "${DIR}"; } > /dev/null 2>&1 && \
-        { ${ECHO} "ezmlm-reject failed to reject null subject"; \
-                exit 100; }
+        { fatal "ezmlm-reject failed to reject null subject"; }
    { make_message  | ${EZBIN}/ezmlm-reject ; } > /dev/null 2>&1 && \
-        { ${ECHO} "ezmlm-reject failed to reject null subject"; \
-                exit 100; }		
+        fatal "ezmlm-reject failed to reject null subject"
 
 # with empty subject
   SUBJECT='(NUll)'
    { make_message  | ${EZBIN}/ezmlm-reject "${DIR}"; } > /dev/null 2>&1 && \
-        { ${ECHO} "ezmlm-reject failed to reject null subject with dir"; \
-                exit 100; }
+        fatal "ezmlm-reject failed to reject null subject with dir"
    { make_message  | ${EZBIN}/ezmlm-reject; } > /dev/null 2>&1 && \
-        { ${ECHO} "ezmlm-reject failed to reject null subject without dir"; \
-                exit 100; }
+        fatal "ezmlm-reject failed to reject null subject without dir"
 # testing -S
   { make_message | ${EZBIN}/ezmlm-reject -S "${DIR}"; } > /dev/null || \
 	fatal "-S switch failed with dir"
@@ -85,11 +74,9 @@ if [ "$SECT" = "1" ]; then
 # with command subject
   SUBJECT='REmOVE'
   { make_message | ${EZBIN}/ezmlm-reject "${DIR}"; } > /dev/null 2>&1 && \
-	{ ${ECHO} "failed to reject command subject with dir"; \
-		exit 100; }
+	fatal "failed to reject command subject with dir"
   { make_message | ${EZBIN}/ezmlm-reject "${DIR}"; } > /dev/null 2>&1 && \
-	{ ${ECHO} "failed to reject command subject without dir"; \
-		exit 100; }
+	fatal "failed to reject command subject without dir"
 # testing -C
   { make_message | ${EZBIN}/ezmlm-reject -C "${DIR}"; } > /dev/null || \
 	fatal "-C switch failed with dir"
@@ -102,32 +89,27 @@ SUBJECT='test'
   CC="$TO"
   TO="nobody@$HOST"
   { make_message | ${EZBIN}/ezmlm-reject "${DIR}"; } > /dev/null || \
-	{ ${ECHO} "failed to accept good Cc: with dir"; \
-		exit 100; }
+	fatal "failed to accept good Cc: with dir"
   { make_message | ${EZBIN}/ezmlm-reject; } > /dev/null || \
-	{ ${ECHO} "failed to accept good Cc: without dir"; \
-		exit 100; }
+	fatal "failed to accept good Cc: without dir"
 
 # Bad To/Cc
   CC="$TO"
   { make_message | ${EZBIN}/ezmlm-reject "${DIR}"; } > /dev/null 2>&1 && \
-		{ ${ECHO} "failed to reject bad To/Cc with dir"; \
-		exit 100; }
+	fatal "failed to reject bad To/Cc with dir"
   if [ "$?" != "100" ]; then
-	${ECHO} "failed to exit 100 on error"; exit 100
+	fatal "failed to exit 100 on error"
   fi
   { make_message | ${EZBIN}/ezmlm-reject -q "${DIR}"; } > /dev/null 2>&1 && \
-		{ ${ECHO} "failed to reject bad To/Cc with dir"; \
-		exit 100; }
+	fatal "failed to reject bad To/Cc with dir"
   if [ "$?" -ne "99" ]; then
-	${ECHO} "-q failed"; exit 100
+	fatal "-q failed"
   fi
 
 # for backwards-compatibility and since we don't know outlocal without
 # dir, ezmlm-reject doesn't check To/Cc when there is no dir
   { make_message | ${EZBIN}/ezmlm-reject; } > /dev/null || \
-		{ ${ECHO} "failed to accept bad To/Cc without dir"; \
-		exit 100; }
+		fatal "failed to accept bad To/Cc without dir"
 
 # testing -T
   { make_message | ${EZBIN}/ezmlm-reject -T "${DIR}"; } > /dev/null || \
@@ -191,8 +173,7 @@ SUBJECT='test'
 # Suppress content-type header
   CONTENT=''
   { make_message | ${EZBIN}/ezmlm-reject "${DIR}"; } > /dev/null || \
-	{ ${ECHO} "headerreject rejected even though header isn't there"; \
-	exit 100; }
+	fatal "headerreject rejected even though header isn't there"
 
   CONTENT='multIpart/mIXed'
 
diff --git a/tests/165-ezmlm-request b/tests/165-ezmlm-request
--- a/tests/165-ezmlm-request
+++ b/tests/165-ezmlm-request
@@ -17,8 +17,7 @@ if [ "$SECT" = "1" ]; then
   ${ECHO} "Subject: qqqq ${SND}@$HOST" >> "${DIR}/__tmp"
   ${EZBIN}/ezmlm-request "${DIR}" < "${DIR}/__tmp" > "${ERR}" 2>&1
   if [ "$?" != "99" ]; then
-	${ECHO} "qqqq command in subject failed to exit 99"
-	exit 100
+	fatal "qqqq command in subject failed to exit 99"
   fi
 
   ${ECHO} "X-num: req1" > "${DIR}/__tmp"
@@ -26,8 +25,7 @@ if [ "$SECT" = "1" ]; then
   ${ECHO} "Subject: ${LOC}-remove-${SND}=${HOST}@${HOST}" >> "${DIR}/__tmp"
   ${EZBIN}/ezmlm-request "${DIR}" < "${DIR}/__tmp" > "${ERR}" 2>&1
   if [ "$?" != "99" ]; then
-	${ECHO} "full ezmlm command in subject failed to exit 99"
-	exit 100
+	fatal "full ezmlm command in subject failed to exit 99"
   fi
 
   ${ECHO} "OK"
diff --git a/tests/220-ezmlm-get b/tests/220-ezmlm-get
--- a/tests/220-ezmlm-get
+++ b/tests/220-ezmlm-get
@@ -39,16 +39,14 @@ ${EZBIN}/ezmlm-get -s "${DIR}" < "${DIR}/__tmp" >/dev/null 2>&1 && \
 	fatal "-s failed to reject -index from non-sub"
 ${EZBIN}/ezmlm-get "${DIR}" < "${DIR}/__tmp" >/dev/null 2>&1
 if [ "$?" -ne "99" ]; then
-	${ECHO} "failed to exit 99 after -index"
-	exit 100
+	fatal "failed to exit 99 after -index"
 fi
 
 ${ECHO} "X-num: index2" > "${DIR}/__tmp"
 SENDER="${DIG}@$HOST"; export SENDER
 ${EZBIN}/ezmlm-get -s "${DIR}" < "${DIR}/__tmp" >/dev/null 2>&1
 if [ "$?" -ne "99" ]; then
-	${ECHO} "-s failed to exit 99 after -index"
-	exit 100
+	fatal "-s failed to exit 99 after -index"
 fi
 
 SENDER="${BNC}@$HOST"; export SENDER
@@ -59,15 +57,13 @@ ${EZBIN}/ezmlm-get -s "${DIR}" < "${DIR}/__tmp" >/dev/null 2>&1 && \
 	fatal "-s failed to reject -get from non-sub"
 ${EZBIN}/ezmlm-get "${DIR}" < "${DIR}/__tmp" >/dev/null 2>&1
 if [ "$?" != "99" ]; then
-	${ECHO} "failed to exit 99 after -get"
-	exit 100
+	fatal "failed to exit 99 after -get"
 fi
 ${ECHO} "X-num: get2" > "${DIR}/__tmp"
 SENDER="${DIG}@$HOST"; export SENDER
 ${EZBIN}/ezmlm-get -s "${DIR}" < "${DIR}/__tmp" >/dev/null 2>&1
 if [ "$?" != "99" ]; then
-	${ECHO} "-s failed to exit 99 after -get"
-	exit 100
+	fatal "-s failed to exit 99 after -get"
 fi
 
 # test formats for -get
@@ -76,16 +72,14 @@ LOCAL="$LOC-getr.2_4"; export LOCAL
 DEFAULT='getr.2_4'; export DEFAULT
 ${EZBIN}/ezmlm-get "${DIR}" < "${DIR}/__tmp" >/dev/null 2>&1
 if [ "$?" != "99" ]; then
-	${ECHO} "failed to exit 99 after -getr"
-	exit 100
+	fatal "failed to exit 99 after -getr"
 fi
 ${ECHO} "X-num: get4" > "${DIR}/__tmp"
 LOCAL="$LOC-getn.2_4"; export LOCAL
 DEFAULT='getn.2_4'; export DEFAULT
 ${EZBIN}/ezmlm-get "${DIR}" < "${DIR}/__tmp" >/dev/null 2>&1
 if [ "$?" != "99" ]; then
-	${ECHO} "failed to exit 99 after -getn"
-	exit 100
+	fatal "failed to exit 99 after -getn"
 fi
 
 ${ECHO} "X-num: get5" > "${DIR}/__tmp"
@@ -93,8 +87,7 @@ LOCAL="$LOC-getv.2_4"; export LOCAL
 DEFAULT='getv.2_4'; export DEFAULT
 ${EZBIN}/ezmlm-get "${DIR}" < "${DIR}/__tmp" >/dev/null 2>&1
 if [ "$?" != "99" ]; then
-	${ECHO} "failed to exit 99 after -getv"
-	exit 100
+	fatal "failed to exit 99 after -getv"
 fi
 
 ${ECHO} "X-num: get6" > "${DIR}/__tmp"
@@ -102,8 +95,7 @@ LOCAL="$LOC-getx.2_4"; export LOCAL
 DEFAULT='getx.2_4'; export DEFAULT
 ${EZBIN}/ezmlm-get "${DIR}" < "${DIR}/__tmp" >/dev/null 2>&1
 if [ "$?" != "99" ]; then
-	${ECHO} "failed to exit 99 after -getx"
-	exit 100
+	fatal "failed to exit 99 after -getx"
 fi
 
 SENDER="${BNC}@$HOST"; export SENDER
@@ -116,15 +108,13 @@ ${EZBIN}/ezmlm-get -s "${DIR}" < "${DIR}/__tmp" >/dev/null 2>&1 && \
 	fatal "-s failed to reject -thread from non-sub"
 ${EZBIN}/ezmlm-get "${DIR}" < "${DIR}/__tmp" >/dev/null 2>&1
 if [ "$?" != "99" ]; then
-	${ECHO} "failed to exit 99 after -thread"
-	exit 100
+	fatal "failed to exit 99 after -thread"
 fi
 ${ECHO} "X-num: thread2" > "${DIR}/__tmp"
 SENDER="${DIG}@$HOST"; export SENDER
 ${EZBIN}/ezmlm-get -s "${DIR}" < "${DIR}/__tmp" >/dev/null 2>&1
 if [ "$?" != "99" ]; then
-	${ECHO} "-s failed to exit 99 after -thread"
-	exit 100
+	fatal "-s failed to exit 99 after -thread"
 fi
 
 ######### digests
@@ -147,27 +137,23 @@ SENDER="${BNC}@$HOST"; export SENDER
 LOCAL="$LOC-dig.code"; export LOCAL
 DEFAULT='dig.code'; export DEFAULT
 ${EZBIN}/ezmlm-get "${DIR}" < "${DIR}/__tmp" >/dev/null 2>&1 && \
-	{ ${ECHO} "failed to reject -dig when no digest code was on cmd-line"
-	  exit 100
-	}
+	fatal "failed to reject -dig when no digest code was on cmd-line"
 if [ -r "${DIR}/dignum" ]; then
-	${ECHO} "script error: dignum exists"; exit 100
+	fatal "script error: dignum exists"
 fi
 ${EZBIN}/ezmlm-get "${DIR}" 'code' < "${DIR}/__tmp" >"${ERR}" 2>&1
 if [ "$?" != "99" ]; then
-	${ECHO} "failed to exit 99 after digest in manager position"
-	exit 100
+	fatal "failed to exit 99 after digest in manager position"
 fi
 if [ ! -r "${DIR}/dignum" ]; then
-	${ECHO} "failed to generate dignum"; exit 100
+	fatal "failed to generate dignum"
 fi
 if [ ! -r "${DIR}/digissue" ]; then
-	${ECHO} "failed to generate digissue"; exit 100
+	fatal "failed to generate digissue"
 fi
 ${EZBIN}/ezmlm-get "${DIR}" 'code' < "${DIR}/__tmp" >/dev/null 2>&1
 if [ "$?" != "99" ]; then
-	${ECHO} "failed to exit 99 when nothing to digest in manager position"
-	exit 100
+	fatal "failed to exit 99 when nothing to digest in manager position"
 fi
 
 ${EZBIN}/ezmlm-get "${DIR}" 'coden' < "${DIR}/__tmp" >/dev/null 2>&1 && \
@@ -187,15 +173,13 @@ ${EZBIN}/ezmlm-get "${DIR}" < "${DIR}/__tmp" >"${ERR}" 2>&1 || \
 # For these, we skip this test.
   if [ -z "$BADUNSET" ]; then
     if [ ! -r "${DIR}/dignum" ]; then
-	${ECHO} "failed to generate dignum after digest in editor"; exit 100
+	fatal "failed to generate dignum after digest in editor"
     fi
 
     ${GREP} "2:" "${DIR}/digissue" >/dev/null 2>&1 || \
-	{ ${ECHO} "failed to update digissue after digest in editor";
-	  exit 100; }
+	fatal "failed to update digissue after digest in editor"
     ${EZBIN}/ezmlm-get "${DIR}" < "${DIR}/__tmp" >"${ERR}" 2>&1 || \
-	{ ${ECHO} "failed to exit 0 when nothing to digest in editor";
-	  exit 100; }
+	fatal "failed to exit 0 when nothing to digest in editor"
   fi
 
 # now from the command line with formats ...
@@ -207,8 +191,7 @@ ${EZBIN}/ezmlm-get "${DIR}" < "${DIR}/__tmp" >/dev/null 2>&1 || \
 ${GREP} "3:" "${DIR}/digissue" >/dev/null 2>&1 || \
 	fatal "failed to update digissue after cmd line digest"
 ${EZBIN}/ezmlm-get "${DIR}" < "${DIR}/__tmp" >/dev/null 2>&1 || \
-	{ ${ECHO} "failed to exit 0 when nothing to digest from cmd line"
-	exit 100; }
+	fatal "failed to exit 0 when nothing to digest from cmd line"
 ${RM} -f "${DIR}/dignum"
 ${ECHO} "X-num: dig4" > "${DIR}/headeradd"
 ${EZBIN}/ezmlm-get -fr "${DIR}" < "${DIR}/__tmp" >/dev/null 2>&1 || \
